use_frameworks!

platform :ios, '8.0'

target 'MultiLanguage_Example' do
  pod 'MultiLanguage', :path => '../'

  target 'MultiLanguage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
